### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 33-toshi** [33-toshi/protospace-33348#1]
URL
https://protospace-33348.herokuapp.com/

**Comment by kouhei-masuda** [comment]
@33-toshi さん、ご提出ありがとうございます‼︎
ご連絡が遅くなり申し訳ありません。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・プロトタイプの投稿に失敗した場合、トップページに飛ぶ形になっている。
(※本来の仕様であれば、投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるようにする）

・他のユーザーが投稿したプロトタイプの編集ページにアクセスできてしまう。
(※本来の仕様であれば、投稿したユーザーだけが編集ページにアクセスできる仕様になる。
ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにする。)

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sakurakoaoi0106** [comment]
33-toshiさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです:sparkles:　
おめでとうございます:tada:

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください:four_leaf_clover:
